[build]
  command = "npm ci --legacy-peer-deps && npm run build:netlify"
  publish = "out"
  
[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_PUBLIC_APP_MODE = "app"
  NEXT_PUBLIC_APP_URL = "https://iridescent-sawine-116743.netlify.app"
  # Environment variables for build
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder-key"

# Simple redirects for static site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

# Environment variables (set these in Netlify dashboard)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY  
# NEXT_PUBLIC_RESEND_API_KEY
# RAZORPAY_KEY_ID
# RAZORPAY_KEY_SECRET
# NEXT_PUBLIC_RAZORPAY_KEY_ID